package generr

import (
	"testing"

	"github.com/andreyvit/diff"
)

func TestGenerator_AppendHeader(t *testing.T) {
	g := &Generator{pkgName: "main"}
	g.AppendHeader()

	exp := "// Code generated by \"generr\"; DO NOT EDIT.\n"
	exp = exp + "package main\n"
	if act := g.buf.String(); act != exp {
		t.Error(diff.LineDiff(exp, act))
	}
}
