// Code generated by "generr"; DO NOT EDIT.
package generr

import "fmt"

func IsTypeNotFound(err error) bool {
	if _, ok := err.(typeNotFound); ok {
		return true
	}
	return false
}

type TypeNotFound struct {
}

func (e *TypeNotFound) TypeNotFound() {
	return
}
func (e *TypeNotFound) Error() string {
	return fmt.Sprint("typeNotFound")
}
