version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/akito0107/generr

    environment:
      DEP_VERSION: 0.5.0
      CC_TEST_REPORTER_ID: 1a73b96326a43b208eceaf09cbf2fe7448d477c83920d2283e1b381e8a2ffa51

    steps:
      - checkout
      - run: curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep && chmod +x $GOPATH/bin/dep
      - run: dep ensure
      - run: make install
      - run:
          name: build
          command: make      
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - run: make test/cover
      - run: ./cc-test-reporter format-coverage --input-type gocov out
      - run: ./cc-test-reporter upload-coverage

