// Code generated by "generr"; DO NOT EDIT.
package e2e

import "fmt"

type NotFound struct {
}

func (e *NotFound) NotFound() {
	return
}
func (e *NotFound) Error() string {
	return fmt.Sprint("notFound")
}
