// Code generated by "generr"; DO NOT EDIT.
package e2e

import "fmt"

func IsNotFound(err error) bool {
	if _, ok := err.(notFound); ok {
		return true
	}
	return false
}

type NotFound struct {
}

func (e *NotFound) NotFound() {
	return
}
func (e *NotFound) Error() string {
	return fmt.Sprint("notFound")
}
