// Code generated by "generr"; DO NOT EDIT.
package e2e

func IsSubpackageNotFound(err error) (bool, string) {
	var info string
	if e, ok := err.(subpackageNotFound); ok {
		info = e.SubpackageNotFound()
		return true, info
	}
	return false, info
}
